### ISSUE TITLE
[FEATURE] Create Author and Blog Model using Gorm.

### ISSUE THREAD

**Issue by sid-js** [sid-js/markive-go#1]
**Is your feature request related to a problem? Please describe.**
For the blog API, we need to create models for Author and Blog

**Describe the solution you'd like**
Create two models : `Author` and `Blog` using GORM

`Author` may have fields like `name`, `bio`, `username`
`Blog` may have fields like `title`, `content`,`createdAt`, `updatedAt`, `author`

Note : GORM needs to be installed and setup in the project and try to follow a scalable folder structure for the models.go file.

**Additional context**
Declaring Models in GORM : https://gorm.io/docs/models.html

**Comment by RISHIKESHk07** [comment]
hey @sid-js  i would like to contribute

**Comment by sid-js** [comment]
Sure please go ahead @RISHIKESHk07 🙌

**Comment by RISHIKESHk07** [comment]
Hey @sid-js  ,should i just create a new folder named "models" and main.go file ,is that fine ?

**Comment by sid-js** [comment]
> Hey @sid-js  ,should i just create a new folder named "models" and main.go file ,is that fine ?
> 

Yep. There's already main.go in src/api. You can make a models folder under api.
